#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
if [ ! -f .env ]; then
  echo 'Missing .env. Run ./scripts/setup-env.sh first.' >&2
  exit 1
fi
set -a
# .env is local shell configuration generated by setup-env.sh; never source untrusted files.
source .env
set +a
if [ -z "${JAVA_HOME:-}" ]; then
  if [ -d .tools/jdk/usr/lib/jvm ]; then
    export JAVA_HOME=$(python3 -c 'from pathlib import Path; print(next(Path(".tools/jdk/usr/lib/jvm").glob("java-21-openjdk-*")).resolve())')
  elif [ "$(uname -s)" = Darwin ]; then
    export JAVA_HOME=$(/usr/libexec/java_home -v 21)
  else
    export JAVA_HOME=$(python3 -c 'from pathlib import Path; import shutil; print(Path(shutil.which("java")).resolve().parents[1])')
  fi
fi
export MAVEN_USER_HOME="${MAVEN_USER_HOME:-$PWD/.cache/maven}"
mkdir -p "$MAVEN_USER_HOME"
arguments=()
if [ -f "$PWD/.cache/maven/settings.xml" ]; then
  arguments+=(--settings "$PWD/.cache/maven/settings.xml")
fi
if [ -f "$PWD/.cache/maven/cloud-cacerts" ]; then
  export MAVEN_OPTS="${MAVEN_OPTS:-} -Djavax.net.ssl.trustStore=$PWD/.cache/maven/cloud-cacerts -Djavax.net.ssl.trustStorePassword=changeit"
fi
cd backend
exec ./mvnw "${arguments[@]}" "-Dmaven.repo.local=$MAVEN_USER_HOME/repository" "$@"
