import { test, expect } from '@playwright/test'

const developmentCopy = /졸업작품|경동대학교|1주차|WEEK|발표|페르소나|API|DB|개발 진행|사용자 흐름/

test('service home renders database examples without presentation or development content', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.activity-card')).toHaveCount(3)
  await expect(page.getByText('공원에서 시작하는 작은 변화', { exact: true })).toBeVisible()
  await expect(page.locator('body')).not.toContainText(developmentCopy)
  await expect(page.getByRole('navigation', { name: '주요 메뉴' }).getByRole('link')).toHaveCount(3)
  await expect(page.getByText('예시 활동', { exact: true })).toHaveCount(3)
  await page.getByRole('button', { name: '주변 활동 살펴보기' }).click()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-home.png', fullPage: true })
})

test('category, query, date and activity type filters narrow examples and can reset', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.activity-card')).toHaveCount(3)
  await page.getByRole('button', { name: '생활 지원', exact: true }).click()
  await expect(page.getByText('조건에 맞는 활동이 없습니다.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '필터 초기화' }).click()
  await page.getByRole('textbox', { name: '활동 또는 장소 검색' }).fill('플로깅')
  await expect(page.locator('.activity-card')).toHaveCount(1)
  await page.getByRole('button', { name: '필터 초기화' }).click()
  await page.getByLabel('활동 날짜로 검색').fill('2026-10-12')
  await expect(page.locator('.activity-card')).toHaveCount(0)
  await page.getByLabel('활동 날짜로 검색').fill('2026-10-11')
  await expect(page.locator('.activity-card')).toHaveCount(3)
  await page.getByLabel('활동 유형', { exact: true }).selectOption('institution')
  await expect(page.locator('.activity-card')).toHaveCount(0)
  await page.getByRole('button', { name: '필터 초기화' }).click()
  await page.getByRole('button', { name: '지도로 보기' }).click()
  await expect(page.getByRole('complementary', { name: '지도 영역' })).toContainText('지도는 준비 중입니다.')
  await expect(page.locator('.activity-card')).toHaveCount(3)
})

test('standalone detail route shows the planned participation steps without accepting applications', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: '공원에서 시작하는 작은 변화 상세 보기' }).click()
  await expect(page).toHaveURL(/#\/activities\/1$/)
  await expect(page.getByRole('heading', { name: '공원에서 시작하는 작은 변화' })).toBeVisible()
  await expect(page.locator('.participation-steps li')).toHaveText(['참가 신청', '승인 또는 대기', '현장 출석', '활동 완료'])
  await expect(page.getByRole('button', { name: '참가 신청 · 준비 중' })).toBeDisabled()
  await expect(page.locator('body')).not.toContainText(developmentCopy)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-detail.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('heading', { name: '공원에서 시작하는 작은 변화' })).toBeVisible()
  await page.goto('/#/activities/999')
  await expect(page.getByRole('heading', { name: '활동을 찾을 수 없습니다' })).toBeVisible()
})

test('create form enforces capacity and duration bounds and never saves an activity', async ({ page }) => {
  const writes: string[] = []
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
  await page.goto('/#/create')
  await expect(page.getByLabel('장소', { exact: true }).locator('option')).toHaveCount(4)
  await page.getByLabel('활동 이름').fill('테스트 공원 정화')
  await page.getByLabel('장소', { exact: true }).selectOption('1')
  await page.getByLabel('활동 날짜', { exact: true }).fill('2026-10-10')
  await page.getByLabel('시작 시간').fill('10:00')
  await page.getByLabel('활동 소개').fill('공원에서 가벼운 쓰레기를 정리합니다.')
  await page.getByLabel('모집 정원').fill('11')
  await page.getByRole('checkbox').nth(0).check()
  await page.getByRole('checkbox').nth(1).check()
  await page.getByRole('button', { name: '입력 내용 확인' }).click()
  await expect(page.locator('.success-message')).toHaveCount(0)
  expect(await page.getByLabel('모집 정원').evaluate((element: HTMLInputElement) => element.validity.rangeOverflow)).toBe(true)
  await page.getByLabel('모집 정원').fill('6')
  await page.getByLabel('활동 시간').fill('181')
  await page.getByRole('button', { name: '입력 내용 확인' }).click()
  await expect(page.locator('.success-message')).toHaveCount(0)
  await page.getByLabel('활동 시간').fill('180')
  await page.getByRole('button', { name: '입력 내용 확인' }).click()
  await expect(page.getByRole('status')).toContainText('등록하거나 저장하지 않습니다.')
  await page.getByLabel('기관 주관 활동', { exact: true }).check()
  await expect(page.getByRole('button', { name: '입력 내용 확인' })).toBeDisabled()
  await expect(page.locator('.inline-notice')).toContainText('기관 확인이 완료된 기관회원')
  expect(writes).toEqual([])
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-create.png', fullPage: true })
})

test('my activities has applicant, organizer and record views without fabricated personal history', async ({ page }) => {
  await page.goto('/#/mine')
  for (const name of ['신청한 활동', '개설한 활동', '활동 기록']) {
    await page.getByRole('tab', { name }).click()
    await expect(page.getByRole('tab', { name })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('tabpanel')).toContainText('로그인과 개인 활동 내역은 준비 중입니다.')
    await expect(page.locator('.activity-card')).toHaveCount(0)
  }
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-mine.png', fullPage: true })
  await page.getByRole('link', { name: '로그인 화면으로' }).click()
  await expect(page).toHaveURL(/#\/login$/)
})

test('signup distinguishes general and institution members and sends no credentials', async ({ page }) => {
  const writes: string[] = []
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
  await page.goto('/#/signup')
  await expect(page.getByRole('radio')).toHaveCount(2)
  await expect(page.getByLabel('기관명', { exact: true })).toHaveCount(0)
  await page.getByRole('radio', { name: /기관회원/ }).check()
  await page.getByLabel('이름', { exact: true }).fill('예시 사용자')
  await page.getByLabel('기관명', { exact: true }).fill('예시 기관')
  await page.getByLabel('기관 연락처').fill('000-0000-0000')
  await page.getByLabel('이메일', { exact: true }).fill('preview@example.invalid')
  await page.getByLabel('비밀번호', { exact: true }).fill('example-only')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('different-example')
  expect(await page.locator('.safety-checks').evaluate(element => element.clientHeight)).toBeLessThan(250)
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: '회원가입 · 준비 중' }).click()
  await expect(page.getByRole('alert')).toHaveText('비밀번호가 일치하지 않습니다.')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('example-only')
  await page.getByRole('button', { name: '회원가입 · 준비 중' }).click()
  await expect(page.getByRole('status')).toContainText('전송하거나 저장하지 않았습니다.')
  await expect(page.locator('body')).not.toContainText(developmentCopy)
  expect(writes).toEqual([])
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-signup.png', fullPage: true })
  await page.getByRole('radio', { name: /일반회원/ }).check()
  await expect(page.getByLabel('기관명', { exact: true })).toHaveCount(0)
  await page.goto('/#/login')
  await page.getByLabel('이메일', { exact: true }).fill('preview@example.invalid')
  await page.getByLabel('비밀번호', { exact: true }).fill('example-only')
  await page.getByRole('button', { name: '로그인 · 준비 중' }).click()
  await expect(page.getByRole('status')).toContainText('로그인은 아직 제공하지 않습니다.')
  expect(writes).toEqual([])
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-login.png', fullPage: true })
})

test('API failure stays visible, can recover and never uses fabricated fallback data', async ({ page }) => {
  await page.route('**/api/**', route => route.fulfill({ status: 503, body: 'unavailable' }))
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('활동 정보를 불러오지 못했습니다.')
  await expect(page.locator('.activity-card')).toHaveCount(0)
  await page.unroute('**/api/**')
  await page.getByRole('button', { name: '다시 시도' }).click()
  await expect(page.locator('.activity-card')).toHaveCount(3)
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('all six service screens work on mobile without horizontal overflow or presentation content', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  for (const path of ['explore', 'activities/1', 'create', 'mine', 'login', 'signup']) {
    await page.goto('/#/' + path)
    await expect(page.locator('body')).not.toContainText(developmentCopy)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.getByRole('navigation', { name: '주요 메뉴' }).getByRole('link', { name: '활동 찾기', exact: true }).click()
  await expect(page.locator('.activity-card')).toHaveCount(3)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: '../docs/screenshots/week-01-mobile.png', fullPage: true })
})
